### PR TITLE
amber add a login method

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
checked!

**Comment by pppluto** [comment]
discuss userName in local or every time need input a userName.
login callback maybe add a line to change the state to re-render the App

**Comment by ghost** [comment]
@MrPluto 
how long you can expose a server api to clinet

**Comment by pppluto** [comment]
actually i send a pr and i dont get any suggestions. and you seems didn't see my suggestions

**Pull request closed without merging**
